layout_spectrum: 0.3014905992895365
typography_spectrum: 0.793613595655188
color:
  brandStrength: 0.8643734168726951
  lightness: 0.7125010003801435
  saturation: 0.502756446134299
  rhythmicContrast: 0.7168886607978493
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
name: FBOC Audio Producer/Designer
analytics:
  twitter: 'https://twitter.com/Balthofficial'
  google: UA-80503771-1
