typography_spectrum: 0.24387311609461904
color:
  brandStrength: 0.9552409145981073
  lightness: 0.8768457809928805
  saturation: 0.5267070841509849
  rhythmicContrast: 0.6941723776981235
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.18848595581948757
analytics:
  twitter: 'https://twitter.com/Balthofficial'
  google: UA-80503771-1
name: FBOC Audio Producer/Designer
title: FBOC
description: Audio Producer/Designer
